### ISSUE TITLE
pgclone ls & restore not working

### ISSUE THREAD

**Issue by lionelwust** [Opus10/django-pgclone#33]
Hello,

Currently unable to make it work:

- Made a dump from a laptop (Windows)
- Sucessfully ls and restore from a cloud deployment after having transfered the dump file via sftp
- Sucessfully transfered the dump file on another laptop and replicating the exact same file structure (.pglcone/blabla/default/none/timestamp.dump)
- From the laptops, unable to get dumps list (ls runs succesfully but returns nothing) and more problematically, unable to to restore from a dump key, restore command seems to run for ever (additional info: I get some psql warning that is ignored some options)

Would happily receive help.

Thanks in advance and have a good day,
Lionel

**Comment by wesleykendall** [comment]
Hey, not sure how I will be able to recreate this. I've gone through a dump/restore flow quite a few times now with no issues. Perhaps there is manual error? (for example, there's a typo in the path posted - `pglcone`)

If SFTP is where you want to store dumps, you might try creating an SFTP storage with `pgclone.storage.Storage`. Would gladly accept that as a backend and can help write tests for it.

Closing this for now, but happy to reopen if there's another way I can recreate this
